services:
  database:
    image: mysql
    container_name: mysql_db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: PesterChum
      MYSQL_USER: chat_admin
      MYSQL_PASSWORD: 5639
  pserver:
    build: .
    container_name: chat_server
    depends_on:
      - database
    ports:
      - 34543:34543

volumes:
  db_data:
